### ISSUE TITLE
TSC Meeting 18-Aug-2016 Retrospective

### ISSUE THREAD

**Issue by nzakas** [eslint/tsc-meetings#10]
Please add your thoughts and comments about the 18-Aug-2016 meeting here.

**Comment by ilyavolodin** [comment]
I actually think the meeting went very well. The only improvement is to not make me take notes, since I'm pretty bad at it:-)

**Comment by gyandeeps** [comment]
I am very bad at taking notes also.

**Comment by nzakas** [comment]
Haha.
