### ISSUE TITLE
TSC meeting 06-May-2021

### ISSUE THREAD

**Issue by btmills** [eslint/tsc-meetings#255]
(Bot didn't autocreate meeting, so creating it manually.)

# Time

UTC Thu 06-May-2021 21:00:
- Los Angeles: Thu 06-May-2021 13:00
- Chicago: Thu 06-May-2021 15:00
- New York: Thu 06-May-2021 16:00
- Madrid: Thu 06-May-2021 22:00
- Moscow: Fri 07-May-2021 00:00
- Tokyo: Fri 07-May-2021 06:00
- Sydney: Fri 07-May-2021 08:00

# Location

https://eslint.org/chat/tsc-meetings

# Agenda

Extracted from:

* Issues and pull requests from the ESLint organization with the ["tsc agenda" label](https://github.com/issues?utf8=%E2%9C%93&q=org%3Aeslint+label%3A%22tsc+agenda%22)
* Comments on this issue

# Invited

- Nicholas C. Zakas (@nzakas) - TSC
- Brandon Mills (@btmills) - TSC
- Milos Djermanovic (@mdjermanovic) - TSC

# Public participation

Anyone is welcome to attend the meeting as observers. We ask that you refrain from interrupting the meeting once it begins and only participate if invited to do so.

**Comment by nzakas** [comment]
Agenda item: Let’s review the v8.0.0 tasks to see if any are blocked on anything (RFCs, decisions, etc.)

**Comment by nzakas** [comment]
Agenda items:

* Let’s review contributor pool candidates for April
* Do we want to start converting other repos to ESM?
* Do we want to remove CLIEngine from the exported API in v8.0.0?

**Comment by nzakas** [comment]
Agenda item: do we want to donate to support the debug module and lint-staged module?
