### ISSUE TITLE
21-Jul-16 retrospective

### ISSUE THREAD

**Issue by nzakas** [eslint/tsc-meetings#6]
How did we do? What can we improve?

**Comment by nzakas** [comment]
One thing I just realized: we didn't fully address the last issue (how to move JSCS compat work along). That's my bad, my brain just stopped functioning. We should be sure to close out each agenda item with a definitive resolution.

**Comment by nzakas** [comment]
It was also unclear that observers could talk if invited to do so, so we should be sure to mention that at the beginning of the meeting.

**Comment by ilyavolodin** [comment]
I think for the most part everything went pretty smoothly this time around, but we also didn't have too much on our plate to discuss. I think JSCS issues approval towards the end was probably unnecessary, but it wasn't too much trouble, so no complains.
